### ISSUE TITLE
Update stable version in repo from 0.0.7 to 0.0.10

### ISSUE THREAD

**Issue by GermanBluefox** [PLCHome/ioBroker.pylontech#2]
# Think about update stable version to 0.0.10
**Version**: stable=**0.0.7** (136 days old) => latest=**0.0.10** (15 days old)
**Installs**: stable=**239** (72.87%), latest=**22** (6.71%), total=**328**

Click to use [developer portal](https://www.iobroker.dev/adapter/pylontech/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2081)

Note: This is an automatically generated message and not personally authored by bluefox!
      Do not close this issue manually as a new issue will be created if condition for update still exists
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response until 07.04.2024 we could decide to update anyway.**

**Comment by PLCHome** [comment]
There was an error message from the forum. I'm still looking for the issue. But it should have come after 0.0.8. Therefore no update for everyone

**Comment by PLCHome** [comment]
Let's see, maybe the problem will go away if the person uses 0.0.10.
