### ISSUE TITLE
System values ​​are not updated

### ISSUE THREAD

**Issue by mrstackit** [PLCHome/ioBroker.pylontech#9]
**Describe the bug**  
The values ​​that are queried via console using pwrsystem are no longer synchronized in the adapter. The values ​​I mean can be seen in the screenshot.

Setup: Pylontech US5000 as Master with US2000C as Slave

![grafik](https://github.com/user-attachments/assets/79b6a705-2020-44f6-b0fd-92b7bb8dbbe7)

**To Reproduce**  
I can't reproduce it because when I create a new adapter the system values ​​don't appear at all.

**Versions:**

- Adapter version: latest
- JS-Controller version: 7.0.0
- Node version: 20.17.0

**Comment by PLCHome** [comment]
Since nothing has changed on the adapter, I suspect it's your environment:
If the checkbox is set in the configuration, the data will not be read otherwise.
If you put the battery into admin/configuration mode, the adapter will no longer work.

**Comment by PLCHome** [comment]
I can't understand it at the moment but system is not part of the query for US batteries. All data listed in the screenshot can be found under Power. SOH is colomb, for example.

**Comment by mrstackit** [comment]
Thanks for the answer

Strange that it then showed me the values. Can you integrate pwrsystem? Because it is the one important query if I want to have the complete status of the entire unit. What is otherwise under power is only the status of the respective individual unit.

I looked at the programming and the pwr part would probably have to be almost identical, just with a pwrsys part added. I want to have the values ​​directly from the system and not have to have something calculated together. I can't find the system_rc and system_soc values ​​in the power part either.
